# Generated by Django 6.1 on 2026-08-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='version',
            field=models.IntegerField(default=1, help_text='Numéro de version du document (incrémenté à chaque signature)'),
        ),
    ]
